/* Auto-generated i18n string table for SMPlusGui */
/* To add a language: add column to STRINGS and increment LANG_COUNT */
#pragma once

#define LANG_DE 0
#define LANG_EN 1
#define LANG_FR 2
#define LANG_ES 3
#define LANG_COUNT 4

typedef enum {
    LS_RUNNING = 0,
    LS_NOT_RUNNING = 1,
    LS_WARNING_SM = 2,
    LS_IMG_OVERRIDES = 3,
    LS_NOTIF_LANG = 4,
    LS_FORCE_HINT = 5,
    LS_KEEP_IMGS = 6,
    LS_SCAN_DEPTH = 7,
    LS_DEPTH_1 = 8,
    LS_DEPTH_2 = 9,
    LS_SCAN_PATHS = 10,
    LS_ADD_PATH = 11,
    LS_RM_MISSING = 12,
    LS_RM_DLC = 13,
    LS_DELAY_SEC = 14,
    LS_KSTUFF_TOG = 15,
    LS_KSTUFF_DLY = 16,
    LS_KSTUFF_NOPAUSE = 17,
    LS_KSTUFF_FMT = 18,
    LS_FAKELIB_HINT = 19,
    LS_PRIORITY = 20,
    LS_PRIO_GAME = 21,
    LS_PRIO_GLOBAL = 22,
    LS_FAKELIB_EXCL = 23,
    LS_EXFAT_BE = 24,
    LS_UFS_BE = 25,
    LS_BIND_ADDR = 26,
    LS_LOCAL_ONLY = 27,
    LS_ALL_IFACES = 28,
    LS_OR = 29,
    LS_MOUNTED_RW = 30,
    LS_SECTOR_FMT = 31,
    LS_ADD_ENTRY = 32,
    LS_ELF_NOT_FOUND = 33,
    LS_SELECT_SM = 34,
    LS_ERROR_STR = 35,
    LS_MANUAL = 36,
    LS_NOTIFS = 37,
    LS_LOADING = 38,
    LS_SAVE = 39,
    LS_RESTORE_DEF = 40,
    LS_CANCEL = 41,
    LS_SAVED = 42,
    LS_QUIET_MODE = 43,
    LS_READ_ONLY = 44,
    LS_MOUNT_DAMAGED = 45,
    LS_BATCH_REG = 46,
    LS_KSTUFF_PAUSE = 47,
    LS_CRASH_TUNE = 48,
    LS_EN_BACKPORT = 49,
    LS_EN_GLOBAL_FL = 50,
    LS_DEBUG_LOG = 51,
    LS_SCAN_INTV = 52,
    LS_PAUSE_IMG = 53,
    LS_PAUSE_DIR = 54,
    LS_LVD_EXFAT_S = 55,
    LS_LVD_UFS_S = 56,
    LS_LVD_PFS_S = 57,
    LS_MD_EXFAT_S = 58,
    LS_MD_UFS_S = 59,
    LS_PORT = 60,
    LS_FL_PATH = 61,
    LS_STAB_WAIT = 62,
    LS_RESET_CONFIRM = 63,
    LS_MIN_VER = 64,
    LS_SCANPATH_HINT = 65,
    LS_SECTOR_HINT = 66,
    LS_MANUAL_HINT = 67,
    LS_FAN_HINT = 68,
    LS_PS5_NO_DL = 69,
    LS_PS5_NO_UL = 70,
    LS_BAK_NAME_PH = 71,
    LS_USB_NO_DRIVE = 72,
    LS_USB_EXPORT_OK = 73,
    LS_USB_IMPORT_OK = 74,
    LS_IMPORT_OK = 75,
    LS_USB_EXPORT = 76,
    LS_USB_IMPORT = 77,
    LS_DL_CURRENT = 78,
    LS_BAK_DL_ALL = 79,
    LS_BAK_USB_ALL = 80,
    LS_BAK_RESTORE = 81,
    LS_BAK_DELETE = 82,
    LS_BAK_DL = 83,
    LS_BAK_CREATE = 84,
    LS_BAK_DEL_ALL = 85,
    LS_CURR_CONFIG = 86,
    LS_BAK_NO_BAKS = 87,
    LS_IMPORT_PC = 88,
    LS_BAK_IMPORT_PC = 89,
    LS_BAD_CONFIG = 90,
    LS_NO_USB_CONFIG = 91,
    LS_USB_NO_BAKS = 92,
    LS_CONFIRM_RESTORE = 93,
    LS_CONFIRM_DELETE = 94,
    LS_CONFIRM_DEL_ALL = 95,
    LS_USB_RESTORE_BAK = 96,
    LS_BAK_SKIPPED = 97,
    LS_COPY_TO_LOCAL = 98,
    LS_MOVE_TO_USB = 99,
    LS_DEL_USB_BAK = 100,
    LS_COPY_ALL_LOCAL = 101,
    LS_MOVE_ALL_USB = 102,
    LS_CONFIRM_DEL_USB = 103,
    LS_CONFIRM_MOVE = 104,
    LS_INTERN_BAKS = 105,
    LS_USB_BAKS = 106,
    LS_MOVE_FROM_USB = 107,
    LS_MOVE_ALL_LOCAL = 108,
    LS_CLEAR_LOG = 109,
    LS_AUTOSTART = 110,
    LS_PREF_ELF = 111,
    LS_COMPAT = 112,
    LS_EXTRA_SCAN = 113,
    LS_SCAN_DEF_HINT = 114,
    LS_SELECT_ELF = 115,
    LS_ICON_FRONT = 116,
    LS_ICON_FRONT_LABEL = 117,
    LS_ALWAYS_RESTART_SM = 118,
    LS_LEGACY_MOUNT = 119,
    LS_EMUS = 120,
    LS_UPDATE_EMUS = 121,
    LS_EMUS_PATH = 122,
    LS_GAMES = 123,
    LS_IMAGES = 124,
    LS_STARTOPTS = 125,
    LS_RESTART_REQUIRED = 126,
    LS_COUNT = 127
} LangStrId;

static int ui_lang = LANG_EN;

static const char *lang_table[LANG_COUNT][LS_COUNT] = {
    /* DE */ {
        "laeuft",
        "nicht aktiv",
        "Warnung: ShadowMount",
        "Image-Overrides",
        "Sprache der Benachrichtigungen",
        "Versucht Images trotzdem zu mounten wenn das Dateisystem Fehler hat. Kann zu Abstürzen führen.",
        "Images permanent eingebunden lassen",
        "Scan-Tiefe",
        "nur erste Unterordner-Ebene",
        "auch eine weitere Ebene tiefer",
        "Scan-Pfade",
        "Pfad hinzufügen",
        "Fehlende Games entfernen",
        "Games mit installiertem DLC entfernen",
        "Verzögerung (Sek.)",
        "Auto-Toggle pausiert kstuff während Spielen um Konflikte zu vermeiden. Autotune erkennt kstuff-bedingte Abstürze und erhöht den Pause-Delay automatisch.",
        "Zeit bis kstuff nach Spielstart reaktiviert wird. Image=25s Direct=15s Standard.",
        "kstuff bleibt aktiv wenn dieses Spiel startet",
        "Titel-ID : eigener Pause-Delay in Sekunden",
        "Fakelib ersetzt PS5-Systemdateien für ein Spiel (z.B. Backport-Bibliotheken). Nur aktivieren wenn Fakelib-Dateien vorhanden sind.",
        "Priorität",
        "game-spezifisch hat Priorität",
        "globale Fakelib hat Priorität",
        "Global-Fakelib für diesen Titel deaktiviert",
        "exFAT Backend",
        "UFS Backend",
        "Bind-Adresse",
        "nur lokal (sicher)",
        "alle Interfaces (Fernzugriff)",
        "oder",
        "wird als Read-Write gemountet",
        "Dateiname des Images : Sektorgrösse in Bytes",
        "Eintrag hinzufügen",
        "SM ELF nicht gefunden",
        "ShadowMount auswaehlen",
        "Fehler",
        "Manuell",
        "Benachrichtigungen",
        "Lade...",
        "Speichern",
        "Standardwerte wiederherstellen",
        "Abbrechen",
        "Gespeichert",
        "Quiet Mode",
        "Nur lesend mounten",
        "Beschädigte Dateisysteme mounten",
        "Batch App-Registrierung (nur bei Bedarf auf FW 12+)",
        "kstuff bei Game-Start pausieren",
        "Crash-Erkennung & Autotune",
        "Backport Fakelib aktivieren",
        "Globale Fakelib aktivieren",
        "Debug-Logging",
        "Scan-Intervall (Sek.)",
        "Pause-Delay Image (Sek.)",
        "Pause-Delay Direct (Sek.)",
        "lvd exFAT-Sektorgrösse",
        "lvd UFS-Sektorgrösse",
        "lvd PFS-Sektorgrösse",
        "md exFAT-Sektorgrösse",
        "md UFS-Sektorgrösse",
        "Port",
        "Pfad zur globalen Fakelib",
        "stability_wait_s (Sek. bis Datei stabil)",
        "Alle Einstellungen auf Standardwerte zuruecksetzen und speichern?",
        "Mindestversion 1.6beta16 empfohlen.",
        "Sobald mindestens ein Pfad gesetzt ist, werden nur diese + eingebaute Pfade gescannt.",
        "Sektorgrössen in Bytes. Standardwerte passen für die meisten Images (nur ändern wenn Spiel nicht startet).",
        "Für Games außerhalb der normalen Scan-Pfade. SM überwacht Änderungen sofort.",
        "Zieltemperatur für den PS5-Lüfter bei Spielstart. \"auto\" lässt das System entscheiden.",
        "Download wird auf PS5 nicht untersützt.",
        "Upload wird auf PS5 nicht unterstützt.",
        "Name (optional)",
        "Kein USB-Laufwerk gefunden.",
        "Auf USB gespeichert.",
        "Von USB importiert.",
        "Import erfolgreich.",
        "Auf USB",
        "Von USB",
        "Config herunterladen",
        "Alle herunterladen",
        "Alle auf USB",
        "Wiederherstellen",
        "L\u00f6schen",
        "Herunterladen (PC)",
        "Erstellen",
        "Alle l\u00f6schen",
        "Aktuelle Config",
        "Noch keine Backups.",
        "Import (PC)",
        "Backup importieren",
        "Ung\u00fcltige Datei (kein ShadowMount-Config).",
        "Keine config.ini auf USB gefunden.",
        "Keine Backups auf USB gefunden.",
        "wiederherstellen?",
        "l\u00f6schen?",
        "Alle Backups l\u00f6schen?",
        "Backup von USB wiederherstellen",
        "ung\u00fcltig",
        "Lokal kopieren",
        "Nach USB verschieben",
        "Von USB l\u00f6schen",
        "Intern kopieren",
        "Alle nach USB",
        "Von USB l\u00f6schen?",
        "Verschieben? Quelle wird nach dem Kopieren gel\u00f6scht.",
        "Interne Backups",
        "USB-Backups",
        "Lokal verschieben",
        "Intern verschieben",
        "Log l\u00f6schen",
        "Auto-Start",
        "Bevorzugte ELF",
        "Kompatibilit\u00e4t",
        "Zus\u00e4tzliche Scan-Verzeichnisse",
        "Standard: /data/pldmgr/payloads/*/, /data/shadowmount/, /mnt/usb0-7/ \u2014 sucht shadowmount*.elf / shadowmountplus*.elf",
        "ELF ausw\u00e4hlen",
        "Icon-Position",
        "Icon immer nach vorne schieben",
        "ShadowMountPlus immer neu starten (auch wenn l\u00e4uft)",
        "Legacy Mount-Profile",
        "Emulatoren",
        "Emulatoren aus Ordner aktualisieren",
        "Emulator-Ordner",
        "Spiele",
        "Images",
        "Startoptionen",
        "Neustart von SMPlusGui erforderlich",
    },
    /* EN */ {
        "running",
        "not running",
        "Warning: ShadowMount",
        "Image Overrides",
        "Notification Language",
        "Tries to mount images even when the filesystem has errors. May cause crashes.",
        "Keep images mounted",
        "Scan depth",
        "first subdirectory level only",
        "one extra nesting level deep",
        "Scan Paths",
        "Add path",
        "Remove missing games",
        "Remove games with installed DLC",
        "Delay (sec)",
        "Auto-toggle pauses kstuff during games to avoid conflicts. Autotune detects kstuff-caused crashes and increases the pause delay automatically.",
        "Time before kstuff reactivates after game launch. Image=25s Direct=15s default.",
        "kstuff stays active when this game launches",
        "Title-ID : custom pause delay seconds",
        "Fakelib overrides PS5 system files for games (e.g. backport libraries). Only enable if fakelib files are present.",
        "Priority",
        "game-specific takes priority",
        "global fakelib takes priority",
        "Disable global fakelib for this title",
        "exFAT Backend",
        "UFS Backend",
        "Bind address",
        "local only (safe)",
        "all interfaces (remote access)",
        "or",
        "mounted as read-write",
        "image filename : sector size in bytes",
        "Add entry",
        "SM ELF not found",
        "Select ShadowMount",
        "Error",
        "Manual",
        "Notifications",
        "Loading...",
        "Save",
        "Restore defaults",
        "Cancel",
        "Saved",
        "Quiet Mode",
        "Read-only mounts",
        "Mount damaged filesystems",
        "Batch app registration (only if needed on FW 12+)",
        "Pause kstuff on game launch",
        "Crash detection & autotune",
        "Enable backport fakelib",
        "Enable global fakelib",
        "Debug Logging",
        "Scan interval (sec)",
        "Pause delay image (sec)",
        "Pause delay direct (sec)",
        "lvd exFAT sector size",
        "lvd UFS sector size",
        "lvd PFS sector size",
        "md exFAT sector size",
        "md UFS sector size",
        "Port",
        "Global fakelib path",
        "stability_wait_s (sec until file stable)",
        "Reset all settings to defaults and save?",
        "Minimum version 1.6beta16 recommended.",
        "Once at least one path is set, only these + built-in paths are scanned (default list replaced).",
        "Sector sizes in bytes. Default values suit most images (only change if game fails to launch).",
        "For games outside normal scan paths. SM detects changes immediately.",
        "Target temperature for PS5 fan at game launch. \"auto\" lets the system decide.",
        "Download not supported on PS5.",
        "Upload not supported on PS5.",
        "Name (optional)",
        "No USB drive found.",
        "Saved to USB.",
        "Imported from USB.",
        "Import successful.",
        "Copy to USB",
        "From USB",
        "Download config",
        "Download all",
        "All to USB",
        "Restore",
        "Delete",
        "Download (PC)",
        "Create",
        "Delete all",
        "Current Config",
        "No backups yet.",
        "Import (PC)",
        "Import backup (PC)",
        "Invalid file (not a ShadowMount config).",
        "No config.ini found on USB.",
        "No backups found on USB.",
        "restore?",
        "delete?",
        "Delete all backups?",
        "Restore backup from USB",
        "invalid",
        "Copy local",
        "Move to USB",
        "Delete from USB",
        "Copy local",
        "Move all to USB",
        "Delete from USB?",
        "Move? Source will be deleted after copying.",
        "Local Backups",
        "USB Backups",
        "Move local",
        "Move local",
        "Clear log",        "Auto-Start",
        "Preferred ELF",
        "Compatibility",
        "Additional scan directories",
        "Default: /data/pldmgr/payloads/*/, /data/shadowmount/, /mnt/usb0-7/ \u2014 searches shadowmount*.elf / shadowmountplus*.elf",
        "Select ELF",
        "Icon Position",
        "Always move icon to front",
        "Always restart ShadowMountPlus (even if running)",
        "Legacy Mount Profiles",
        "Emulators",
        "Update emulators from folder",
        "Emulators path",
        "Games",
        "Images",
        "Start Options",
        "Restart SMPlusGui to apply",
    },
    /* FR */ {
        "actif",
        "inactif",
        "Avertissement : ShadowMount",
        "Image-Overrides",
        "Langue des notifications",
        "Tente de monter les images même en cas d'erreurs. Peut provoquer des plantages.",
        "Garder les images montées",
        "Profondeur d'analyse",
        "premier niveau uniquement",
        "un niveau supplémentaire",
        "Chemins d'analyse",
        "Ajouter un chemin",
        "Supprimer les jeux manquants",
        "Supprimer les jeux avec DLC installé",
        "Délai (s)",
        "Le basculement auto met kstuff en pause pendant les jeux. L'autotune détecte les plantages et augmente le délai automatiquement.",
        "Temps avant la réactivation de kstuff. Image=25s Direct=15s par défaut.",
        "kstuff reste actif quand ce jeu démarre",
        "ID de titre : délai de pause personnalisé en secondes",
        "Fakelib remplace les fichiers système PS5 pour les jeux. N'activer que si des fichiers fakelib sont présents.",
        "Priorité",
        "le jeu spécifique est prioritaire",
        "la fakelib globale est prioritaire",
        "Désactiver la fakelib globale pour ce titre",
        "Backend exFAT",
        "Backend UFS",
        "Adresse d'écoute",
        "local uniquement (sécurisé)",
        "toutes les interfaces (accès distant)",
        "ou",
        "monté en lecture-écriture",
        "nom du fichier image : taille de secteur en octets",
        "Ajouter une entrée",
        "SM ELF introuvable",
        "Sélectionner ShadowMount",
        "Erreur",
        "Manuel",
        "Notifications",
        "Chargement...",
        "Enregistrer",
        "Restaurer les valeurs",
        "Annuler",
        "Enregistré",
        "Mode silencieux",
        "Montage en lecture seule",
        "Monter les systèmes de fichiers endommagés",
        "Enregistrement par lot (seulement si nécessaire sur FW 12+)",
        "Mettre kstuff en pause au lancement du jeu",
        "Détection de plantage & autotune",
        "Activer la fakelib de backport",
        "Activer la fakelib globale",
        "Journal de débogage",
        "Intervalle d'analyse (s)",
        "Délai de pause image (s)",
        "Délai de pause direct (s)",
        "lvd exFAT sector size",
        "lvd UFS sector size",
        "lvd PFS sector size",
        "md exFAT sector size",
        "md UFS sector size",
        "Port",
        "Chemin de la fakelib globale",
        "stability_wait_s (s jusqu'à stabilité)",
        "Réinitialiser tous les paramètres aux valeurs par défaut ?",
        "Version minimale 1.6beta16 recommandée.",
        "Dès qu'un chemin est défini, seuls ces chemins + les intégrés sont analysés.",
        "Tailles de secteur en octets. Les valeurs par défaut conviennent à la plupart des images.",
        "Pour les jeux hors des chemins normaux. SM détecte les changements immédiatement.",
        "Température cible du ventilateur PS5 au lancement. \"auto\" laisse le système décider.",
        "Téléchargement non pris en charge sur PS5.",
        "Téléversement non pris en charge sur PS5.",
        "Nom (optionnel)",
        "Aucun lecteur USB trouvé.",
        "Enregistré sur USB.",
        "Importé depuis USB.",
        "Importation réussie.",
        "Copier sur USB",
        "Importer depuis USB",
        "Télécharger config",
        "Tout télécharger",
        "Tout copier sur USB",
        "Restaurer",
        "Supprimer",
        "Télécharger (PC)",
        "Créer",
        "Tout supprimer",
        "Config actuelle",
        "Aucune sauvegarde.",
        "Importer (PC)",
        "Importer sauvegarde (PC)",
        "Fichier invalide (pas une config ShadowMount).",
        "Pas de config.ini trouv\u00e9 sur USB.",
        "Aucune sauvegarde trouv\u00e9e sur USB.",
        "restaurer ?",
        "supprimer ?",
        "Supprimer toutes les sauvegardes ?",
        "Restaurer sauvegarde (USB)",
        "invalides",
        "Copier local",
        "D\u00e9placer vers USB",
        "Supprimer de USB",
        "Copier local",
        "Tout vers USB",
        "Supprimer de USB ?",
        "D\u00e9placer ? La source sera supprim\u00e9e apr\u00e8s la copie.",
        "Sauvegardes USB",
        "D\u00e9placer local",
        "D\u00e9placer local",
        "Cr\u00e9er sur USB",
        "Effacer le journal",
        "D\u00e9marrage auto",
        "ELF pr\u00e9f\u00e9r\u00e9",
        "Compatibilit\u00e9",
        "R\u00e9pertoires d'analyse suppl\u00e9mentaires",
        "D\u00e9faut : /data/pldmgr/payloads/*/, /data/shadowmount/, /mnt/usb0-7/ \u2014 cherche shadowmount*.elf / shadowmountplus*.elf",
        "S\u00e9lectionner ELF",
        "Position de l'ic\u00f4ne",
        "Toujours mettre l'ic\u00f4ne au premier plan",
        "Toujours red\u00e9marrer ShadowMountPlus (m\u00eame si actif)",
        "Profils de montage h\u00e9rit\u00e9s",
        "\u00c9mulateurs",
        "Mettre \u00e0 jour les \u00e9mulateurs depuis le dossier",
        "Dossier des \u00e9mulateurs",
        "Jeux",
        "Images",
        "Options de d\u00e9marrage",
        "Red\u00e9marrer SMPlusGui pour appliquer",
    },
    /* ES */ {
        "activo",
        "inactivo",
        "Advertencia: ShadowMount",
        "Reemplazos de imagen",
        "Idioma de notificaciones",
        "Intenta montar imágenes incluso con errores del sistema de archivos. Puede causar cuelgues.",
        "Mantener imágenes montadas",
        "Profundidad de análisis",
        "solo el primer nivel",
        "un nivel adicional",
        "Rutas de análisis",
        "Agregar ruta",
        "Eliminar juegos faltantes",
        "Eliminar juegos con DLC instalado",
        "Retraso (s)",
        "El basculamiento auto pausa kstuff durante los juegos. El autotune detecta cuelgues y aumenta el retraso automáticamente.",
        "Tiempo hasta la reactivación de kstuff. Image=25s Direct=15s predeterminado.",
        "kstuff permanece activo cuando este juego se inicia",
        "ID de título : retraso de pausa personalizado en segundos",
        "Fakelib reemplaza los archivos del sistema PS5 para los juegos. Solo activar si hay archivos fakelib presentes.",
        "Prioridad",
        "el juego específico tiene prioridad",
        "la fakelib global tiene prioridad",
        "Deshabilitar fakelib global para este título",
        "Backend exFAT",
        "Backend UFS",
        "Dirección de escucha",
        "solo local (seguro)",
        "todas las interfaces (acceso remoto)",
        "o",
        "montado en lectura-escritura",
        "nombre de archivo de imagen : tamaño de sector en bytes",
        "Agregar entrada",
        "SM ELF no encontrado",
        "Seleccionar ShadowMount",
        "Error",
        "Manual",
        "Notificaciones",
        "Cargando...",
        "Guardar",
        "Restaurar valores",
        "Cancelar",
        "Guardado",
        "Modo silencioso",
        "Montaje de solo lectura",
        "Montar sistemas de archivos dañados",
        "Registro por lotes (solo si es necesario en FW 12+)",
        "Pausar kstuff al iniciar el juego",
        "Detección de cuelgues & autotune",
        "Activar fakelib de backport",
        "Activar fakelib global",
        "Registro de depuración",
        "Intervalo de análisis (s)",
        "Retraso de pausa imagen (s)",
        "Retraso de pausa directo (s)",
        "lvd exFAT sector size",
        "lvd UFS sector size",
        "lvd PFS sector size",
        "md exFAT sector size",
        "md UFS sector size",
        "Puerto",
        "Ruta de la fakelib global",
        "stability_wait_s (s hasta estabilidad)",
        "¿Restablecer todos los ajustes a los valores predeterminados?",
        "Versión mínima 1.6beta16 recomendada.",
        "Si hay una ruta, solo esas + las integradas serán analizadas.",
        "Tamaños de sector en bytes. Valores predeterminados para la mayoría de las imágenes.",
        "Para juegos fuera de las rutas normales. SM detecta los cambios de inmediato.",
        "Temperatura objetivo del ventilador PS5 al inicio. \"auto\" deja que el sistema decida.",
        "Descarga no compatible en PS5.",
        "Subida no compatible en PS5.",
        "Nombre (opcional)",
        "No se encontró unidad USB.",
        "Guardado en USB.",
        "Importado desde USB.",
        "Importación exitosa.",
        "A USB",
        "Desde USB",
        "Descargar config",
        "Descargar todo",
        "Copiar todo a USB",
        "Restaurar",
        "Eliminar",
        "Descargar (PC)",
        "Crear",
        "Eliminar todo",
        "Config actual",
        "Sin copias de seguridad.",
        "Importar (PC)",
        "Importar copia (PC)",
        "Archivo inv\u00e1lido (no es config de ShadowMount).",
        "No hay config.ini en USB.",
        "Sin copias de seguridad en USB.",
        "¿restaurar?",
        "\u00bfeliminar?",
        "\u00bfEliminar todas las copias?",
        "Restaurar copia (USB)",
        "inv\u00e1lidos",
        "Copiar local",
        "Mover a USB",
        "Eliminar de USB",
        "Copiar local",
        "Mover todo a USB",
        "\u00bfEliminar de USB?",
        "\u00bfMover? El origen se eliminar\u00e1 tras copiar.",
        "Copias locales",
        "Copias USB",
        "Mover local",
        "Mover local",
        "Borrar log",
        "Inicio autom\u00e1tico",
        "ELF preferido",
        "Compatibilidad",
        "Directorios de an\u00e1lisis adicionales",
        "Predeterminado: /data/pldmgr/payloads/*/, /data/shadowmount/, /mnt/usb0-7/ \u2014 busca shadowmount*.elf / shadowmountplus*.elf",
        "Seleccionar ELF",
        "Posici\u00f3n del icono",
        "Siempre mover el icono al frente",
        "Siempre reiniciar ShadowMountPlus (incluso si est\u00e1 activo)",
        "Perfiles de montaje heredados",
        "Emuladores",
        "Actualizar emuladores desde la carpeta",
        "Ruta de emuladores",
        "Juegos",
        "Im\u00e1genes",
        "Opciones de inicio",
        "Reiniciar SMPlusGui para aplicar",
    }
};

#define L(id) lang_table[ui_lang][id]
